"""sms channel

Revision ID: 4b10489294d9
Revises: c66fc0950459
Create Date: 2026-07-19 18:18:29.986975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b10489294d9'
down_revision: Union[str, None] = 'c66fc0950459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# SQLite batch mode recreates the table for alter_column; the existing FKs are
# unnamed, so give them names during recreate via a naming convention.
NAMING = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('from_number', sa.String(length=40), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('secret_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_profiles_name'), ['name'], unique=True)

    with op.batch_alter_table('campaigns', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=10), nullable=False, server_default='email'))
        batch_op.add_column(sa.Column('sms_profile_id', sa.Integer(), nullable=True))
        batch_op.alter_column('profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_campaigns_sms_profile_id_sms_profiles', 'sms_profiles', ['sms_profile_id'], ['id']
        )

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_results_short_code'), ['short_code'], unique=True)

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=10), nullable=False, server_default='email'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('channel')

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_short_code'))
        batch_op.drop_column('phone')
        batch_op.drop_column('short_code')

    with op.batch_alter_table('campaigns', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.drop_constraint('fk_campaigns_sms_profile_id_sms_profiles', type_='foreignkey')
        batch_op.alter_column('profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('sms_profile_id')
        batch_op.drop_column('channel')

    with op.batch_alter_table('sms_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_profiles_name'))

    op.drop_table('sms_profiles')
    # ### end Alembic commands ###
