"""api sending profiles

Revision ID: 729b2db646e7
Revises: a1e6a99a5342
Create Date: 2026-07-19 12:16:57.359661
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '729b2db646e7'
down_revision: Union[str, None] = 'a1e6a99a5342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sending_profiles', schema=None) as batch_op:
        # server_default so existing SMTP profiles get 'smtp'; NOT NULL is then safe.
        batch_op.add_column(sa.Column('kind', sa.String(length=10), nullable=False, server_default='smtp'))
        batch_op.add_column(sa.Column('api_provider', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('api_key_encrypted', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('api_domain', sa.String(length=255), nullable=True))
        batch_op.alter_column('host',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sending_profiles', schema=None) as batch_op:
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('host',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('api_domain')
        batch_op.drop_column('api_key_encrypted')
        batch_op.drop_column('api_provider')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
