"""must_change_password

Revision ID: a1e6a99a5342
Revises: f0ec97c3b333
Create Date: 2026-07-19 09:47:33.168867
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1e6a99a5342'
down_revision: Union[str, None] = 'f0ec97c3b333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default so existing rows get a value; NOT NULL is then safe.
        batch_op.add_column(
            sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
