"""envelope sender

Revision ID: c66fc0950459
Revises: 729b2db646e7
Create Date: 2026-07-19 15:27:40.460437
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c66fc0950459'
down_revision: Union[str, None] = '729b2db646e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sending_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envelope_sender', sa.String(length=320), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sending_profiles', schema=None) as batch_op:
        batch_op.drop_column('envelope_sender')

    # ### end Alembic commands ###
